name: Fetch new opinions

on:
  workflow_dispatch:         # lets you press “Run workflow”

env:
  USER_AGENT: ${{ secrets.USER_AGENT }}   # (only this one line under env)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install -r requirements.txt
      - run: python fetch_and_post.py
      - run: |
          git config user.email "bot@users.noreply.github.com"
          git config user.name  "Opinion-Bot"
          git add _posts || true
          git diff --cached --quiet || git commit -m "add new opinions"
          git push
